#!/bin/bash

set -e

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/dan/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/dan/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install git
brew install gh

cat <<- 'EOF' > ~/.zshrc
export PATH="/Users/dan/.local/bin:$PATH"
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '(%b)'

# Set up the prompt (with git branch name)
setopt PROMPT_SUBST
PROMPT='%F{118}%n%F{119}@%F{120}%m%F{121}:%F{122}${PWD/#$HOME/~} %F{123}${vcs_info_msg_0_}%F{219}$ %f'

alias c='cd ~/src/sona/'

export ERL_AFLAGS="-kernel shell_history enabled"
export EDITOR=vim

alias br="git branch --sort=-committerdate"

autoload -Uz compinit && compinit

EOF

echo "--------------------------------------------------------------------------------------"
echo "You need to resource your .zshrc file, either type '. ~/.zshrc' or logout and back in"
echo "--------------------------------------------------------------------------------------"
