#!/bin/bash
mkdir -p ~/.bashrc.d
echo """
     #!/bin/bash
     parse_git_branch() {
       git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
     }
     export PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;35m\]\$(parse_git_branch)\e[39m\\$ '
     """ > ~/.bashrc.d/dan


LINE='[ -f ~/.bashrc.d/dan ] && . ~/.bashrc.d/dan'
FILE=~/.bashrc
grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"

