#!/bin/bash

sudo echo "a prompt for sudo" >/dev/null
sudo apt update
sudo apt install python3-dev python3-pip python3-setuptools -y
sudo pip3 install thefuck

mkdir -p ~/.bashrc.d
echo """
     #!/bin/bash
     parse_git_branch() {
       git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
     }
     export PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;35m\]\$(parse_git_branch)\e[39m\\$ '
     eval $(thefuck --alias)
     """ > ~/.bashrc.d/dan


LINE='[ -f ~/.bashrc.d/dan ] && . ~/.bashrc.d/dan'
FILE=~/.bashrc
grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
echo "--------------------------------------------------------------------------------------"
echo "You need to resource your bashrc file, either type '. ~/.bashrc' or logout and back in"
echo "--------------------------------------------------------------------------------------"
