#!/bin/bash

set -e

sudo echo "a prompt for sudo" >/dev/null
brew install thefuck
brew install gh

mkdir -p ~/.bashrc.d
echo """
     #!/bin/bash
     parse_git_branch() {
       git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
     }
     export PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;35m\]\$(parse_git_branch)\[\033[00m\]\$ '
     export VISUAL=vim
     export EDITOR=vim
     export LC_ALL=en_GB.UTF-8
     export LANG=en_GB.UTF-8
     export LANGUAGE=en_GB.UTF-8
     eval $(thefuck --alias)
     alias p='cd /home/dan/src/platform'
     export PATH=/home/dan/src/platform/assets/node_modules/.bin:$PATH
     export ERL_AFLAGS="-kernel shell_history enabled -kernel shell_history_file_bytes 1024000"
     """ > ~/.bashrc.d/dan


LINE='[ -f ~/.bashrc.d/dan ] && . ~/.bashrc.d/dan'
FILE=~/.bashrc
grep -qF -- "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
echo "--------------------------------------------------------------------------------------"
echo "You need to resource your bashrc file, either type '. ~/.bashrc' or logout and back in"
echo "--------------------------------------------------------------------------------------"
